#!/usr/sbin/nft -f

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0;
        policy drop;

        # allow loopback
        iif lo accept

        # allow established connections
        ct state established,related accept

        # allow ssh from public admin IP and VPN
        ip saddr <PUBLIC_IP> tcp dport 22 accept
        ip saddr 10.8.0.0/24 tcp dport 22 accept
	
        # allow RDP from VPN
        ip saddr 10.8.0.0/24 tcp dport 3389 accept

        # allow proxmox web from public admin IP and VPN
        ip saddr <PUBLIC_IP> tcp dport 8006 accept
        ip saddr 10.8.0.0/24 tcp dport 8006 accept

        # allow OpenVPN
        udp dport 1194 accept

        # optional: allow ping to host
        ip protocol icmp accept
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;

        # allow established/related forwarding
        ct state established,related accept

        # VPN -> vmbr1/vmbr2/vmbr3 : SSH only
        iifname "tun0" oifname {"vmbr1", "vmbr2", "vmbr3"} ip saddr 10.8.0.0/24 tcp dport 22 accept

	# VPN -> vmbr1/vmbr2/vmbr3 : 80/443
        iifname "tun0" oifname {"vmbr1", "vmbr2", "vmbr3"} ip saddr 10.8.0.0/24 tcp dport 80 accept
	iifname "tun0" oifname {"vmbr1", "vmbr2", "vmbr3"} ip saddr 10.8.0.0/24 tcp dport 443 accept

	# VPN -> vmbr1/vmbr2/vmbr3 : RDP only
        iifname "tun0" oifname {"vmbr1", "vmbr2"} ip saddr 10.8.0.0/24 tcp dport 3389 accept
        iifname "tun0" oifname {"vmbr1"} ip saddr 10.8.0.0/24 tcp dport 3390 accept

        # VPN -> winbox
        iifname "tun0" oifname "vmbr2" ip saddr 10.8.0.0/24 tcp dport 8291 accept
        

        # vmbr1 -> Internet : DNS
        iifname "vmbr1" oifname "vmbr0" udp dport 53 accept
        iifname "vmbr1" oifname "vmbr0" tcp dport 53 accept

        # vmbr1 -> Internet : APT over HTTPS
        iifname "vmbr1" oifname "vmbr0" tcp dport 443 accept

        # optional: enable only if any repo still uses http://
        iifname "vmbr1" oifname "vmbr0" tcp dport 80 accept

        # optional: NTP for vmbr1
        # iifname "vmbr1" oifname "vmbr0" udp dport 123 accept

	#vmbr1 <--> vmbr2 <--> vmbr3  traffic 
    	iifname "vmbr1" oifname {"vmbr2", "vmbr3"} accept 
    	iifname "vmbr2" oifname {"vmbr1", "vmbr3"} accept
	iifname "vmbr3" oifname {"vmbr1", "vmbr2"} accept
	#vmbr4 test
	#iifname "vmbr4" oifname {"vmbr2","vmbr3"} accept
	#iifname {"vmbr2","vmbr3"} oifname "vmbr4" accept
	#iifname "vmbr4" oifname "vmbr0" tcp dport 443 accept
	#iifname "vmbr4" oifname "vmbr0" tcp dport 53 accept
	#iifname "vmbr4" oifname "vmbr0" tcp dport 80 accept
        # vmbr2 -> Internet : DNS
        iifname "vmbr2" oifname "vmbr0" udp dport 53 accept
        iifname "vmbr2" oifname "vmbr0" tcp dport 53 accept

        # vmbr2 -> Internet : APT over HTTPS
        iifname "vmbr2" oifname "vmbr0" tcp dport 443 accept

        # optional: enable only if any repo still uses http://
        iifname "vmbr2" oifname "vmbr0" tcp dport 80 accept

        # optional: NTP for vmbr2
        # iifname "vmbr2" oifname "vmbr0" udp dport 123 accept
    	
        
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100;

        # OpenVPN clients to Internet through public bridge
        oifname "vmbr0" ip saddr 10.8.0.0/24 masquerade

        # vmbr1 to Internet through public bridge
        oifname "vmbr0" ip saddr 10.2.0.0/24 masquerade

        # vmbr2 to Internet through public bridge
        oifname "vmbr0" ip saddr 10.3.0.0/24 masquerade
	
	# optional: vmbr2 return to tun0 (snat)
	# oifname "vmbr2" ip saddr 10.8.0.0/24 ip daddr 10.3.0.0/24 snat to 10.3.0.254
	

    }
}

