---
# Zeek sensor-specific settings.
zeek_version: "8.0.6"
zeek_parent_interface: "ens19"
zeek_vlan_id: 999
zeek_capture_interface: "{{ zeek_parent_interface }}.{{ zeek_vlan_id }}"

# The precompiled artifact you already created.
zeek_artifact: "{{ inventory_dir }}/../artifacts/zeek-8.0.6/zeek-8.0.6-ubuntu24.04-amd64.tar.gz"
wazuh_agent_config_template: "zeek-agent-ossec.conf.j2"